### ISSUE TITLE
Fix autogeneration of DecomposableK.hs

### ISSUE THREAD

**Issue by harendra-kumar** [harendra-kumar/unicode-transforms#13]
Commit be05072 fixed the llvm build by splitting the big list in `DecomposableK.hs` into two smaller lists. However, this file is an autogenerated file, generated from the unicode database using the `unicode-data/UCD2Haskell.hs` script, therefore the fix should be made [in the function called here](https://github.com/harendra-kumar/unicode-transforms/blob/master/unicode-data/UCD2Haskell.hs#L370) in this script instead and the file should be generated by that script. 

cc @brent80 in case you got time to fix this.

**Comment by brent80** [comment]
https://github.com/harendra-kumar/unicode-transforms/pull/14

**Comment by harendra-kumar** [comment]
Fixed via e5de0f5fb65fa2608fa2f01c074a79b3417310a2. Thanks @brent80 !
