### ISSUE TITLE
add to hackage

### ISSUE THREAD

**Issue by ppelleti** [harendra-kumar/unicode-transforms#3]
Hi, do you have plans to add this package to hackage soon?

I've written a package `normalization-insensitive` (essentially a clone of the `case-insensitive` package, but for normalization instead of case) which depends on `unicode-transforms`, but before I can put my package on hackage, its dependencies need to be on hackage first.

Thanks!

**Comment by harendra-kumar** [comment]
I essentially created this package to fix commercialhaskell/stack#1810 . I do have plans to put it on hackage but held it for two reasons:
* I have been playing with Haskell implementation of normalization. I have got that to work faster than the C implementation that this package is using currently. I thought I would upload it to hackage once I am done with that. But as along as the API remains the same it should not matter.
* I was wondering if it would make sense to integrate the haskell implementation in the `text` package itself (bos/text#148) rather than creating a separate package. But I don't know whether that can happen anytime soon since I have not got any update on that issue yet. Maybe I should think about it only after I am done with the Haskell implementation.

How soon do you need it? Can I have a look at your package?

**Comment by ppelleti** [comment]
Thanks for the info!

I don't have any specific timetable; I was just curious what your plans were.

I've pushed my repository to [ppelleti/normalization-insensitive][1], so you can view it there.  It's a pretty direct port of [basvandijk/case-insensitive][2].  I still have some work to do, such as porting the benchmarks.

Currently, I'm using `normalization-insensitive` in a personal project that involves synchronizing files between my Android phone and my Mac laptop.  Linux (and thus Android) uses NFC in its filesystem, and Mac OS X uses NFD in its filesystem, so in order to accurately determine which files correspond, I must do normalization insensitive comparison.

I'd just thought `normalization-insensitive` might also be useful to other people, but I'm not in any particular hurry to release it.

[1]: /ppelleti/normalization-insensitive
[2]: /basvandijk/case-insensitive

**Comment by harendra-kumar** [comment]
That looks cool! I wanted something like that. The only thing I found earlier was `text-normal`, your approach seems more general and works for all string like data types. I think it will be very useful. In fact that's the way most end users should be using normalization.  

BTW, was there a specific reason for choosing NFKD over NFD or NFC?

I will try to put my package on hackage soon. We can switch the underlying implementation to Haskell even later as long as the API remains the same.

Maybe at some point all the unicode related packages should be consolidated to make it easier for the users.

**Comment by ppelleti** [comment]
No, there wasn't a compelling reason to choose NFKD, and I'd be happy to change it to one of the other forms, but my reasoning was like this:

* I chose NFKD over NFD because my understanding is that NFKD normalizes a few additional "compatibility" code points, such as ligatures.  But my logic was just that it might be helpful, and shouldn't hurt anything.  I'm not using any compatibility code points myself.

* I chose NFKD/NFD over KFKC/NFC on the thought that the sort order might be a little more sane in decomposed form than in composed form.

But both of these are fairly weak reasons.  And I haven't benchmarked the various normalization forms to see which is fastest.  That could be a more compelling reason to choose one over the other.

I'm certainly open to changing it, though, and would welcome any thoughts you have on the matter.

**Comment by harendra-kumar** [comment]
[Unicode website] (http://unicode.org/faq/normalization.html) suggests NFC for most use cases. There is no sort order in composed forms. In decomposed forms normalization has to always keep the combining chars sorted in a canonical order, so that does not matter either.

**Comment by ppelleti** [comment]
OK, I switched it to NFC.  There is still a sort order, though, because the `Ord` instance is necessary to use normalization-insensitive strings in sets and maps, which I consider to be one of the main use cases.  This ordering leaks out to the user a little bit, if you print the set or map in order.

**Comment by harendra-kumar** [comment]
Ah! I completely misunderstood sort order earlier. I was thinking about the ordering of the combining chars for normalization. My bad. Yeah the sorting order of strings will depend on the normalization form since we are sorting on individual char values.

**Comment by harendra-kumar** [comment]
I created a REL0.1 branch for uploading to hackage. Please take a look. I have changed Data.Unicode.Normalize to Data.Unicode.Types, you will need to make corresponding changes at your end. I tested it on Linux/mac/windows with ghc 7.8/7.10/8.0. Try this with your package and I will upload if all works well.

**Comment by harendra-kumar** [comment]
I uploaded a candidate tarball here https://hackage.haskell.org/package/unicode-transforms-0.1.0.0/candidate. Can you try that?

**Comment by ppelleti** [comment]
I've tried your candidate tarball with my package with ghc 7.8, 7.10, and 8.0, and it all looks good.

**Comment by harendra-kumar** [comment]
Thanks, I will wait a couple more days and then publish it.

**Comment by harendra-kumar** [comment]
version 0.1.0.1 is on hackage - https://hackage.haskell.org/package/unicode-transforms .
